// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaJ-ksYjUKPQ-sS9rkngUdVwRW0Cr6n30',
    appId: '1:802615696691:web:11e3853b9d4631f3d93246',
    messagingSenderId: '802615696691',
    projectId: 'unicv-chat-ads',
    authDomain: 'unicv-chat-ads.firebaseapp.com',
    storageBucket: 'unicv-chat-ads.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXweU-CyeROSVaC4FXRzKIPy9Jws1Qoog',
    appId: '1:802615696691:android:d3456538d80c9473d93246',
    messagingSenderId: '802615696691',
    projectId: 'unicv-chat-ads',
    storageBucket: 'unicv-chat-ads.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB09Me13A-cHmGrVDpJWWurDBmA4_AffTM',
    appId: '1:802615696691:ios:c788fdfdeedcc8f1d93246',
    messagingSenderId: '802615696691',
    projectId: 'unicv-chat-ads',
    storageBucket: 'unicv-chat-ads.appspot.com',
    iosBundleId: 'com.example.telaLogin2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB09Me13A-cHmGrVDpJWWurDBmA4_AffTM',
    appId: '1:802615696691:ios:250bd453229bd185d93246',
    messagingSenderId: '802615696691',
    projectId: 'unicv-chat-ads',
    storageBucket: 'unicv-chat-ads.appspot.com',
    iosBundleId: 'com.example.telaLogin2.RunnerTests',
  );
}
